eureka:
  client:
    service-url:
      defaultzone: http://localhost:8761/eureka


server:
  port: 8080
spring:
  application:
    name: zuul

#公开所有的端点
management:
  endpoints:
    web:
      exposure:
        include: "*"
#自行设置路由
zuul:
  routes:
    goods-ui: /goods/**
    customer-ui: /customer/**
