server:
  port: 9002

spring:
  application:
    name: customer-ui
eureka:
  client:
    service-url:
      defaultzone: http://localhost:8761/eureka
hystrix:
  command:
    default:
      execution:
        isolationn:
          thread:
            timeoutInMilliseconds: 1000
feign:
  hystrix:
    enabled: true
